### PR TITLE
fix(snapshots): raise the per snapshot item limit

### LINKED ISSUE #8325: state-sync cannot restore payloads larger than 64MB
## Describe the bug
[cosmos-sdk hardcodes a maximum payload size of 64MB](https://github.com/agoric-labs/cosmos-sdk/blob/67760b3d3ee572f814385d1208d9f5764cd9ee3d/snapshots/manager.go#L24) used when [restoring from a state-sync snapshot](https://github.com/agoric-labs/cosmos-sdk/blob/67760b3d3ee572f814385d1208d9f5764cd9ee3d/snapshots/stream.go#L87). 

Unfortunately mainnet has an artifact larger than that (the boostrap vat's first transcript span), resulting in the inability to restore from state-sync.

The error is pretty cryptic, simply:
```
ERR failed to restore snapshot err="extension swingset restore: short buffer"
ERR State sync failed err="state sync aborted" module=statesync
```

There is no stack trace available being a built-in error, but it's returned from the [protobuf io package](https://github.com/gogo/protobuf/blob/f67b8970b736e53dbd7d0a27146c8f1ac52f74e5/io/varint.go#L115-L117) 

## To Reproduce
Try to restore from state-sync using `agoric-upgrade-11` software

## Expected behavior
Restore from state-sync successful.

## Platform Environment
`agoric-upgrade-11`

## Additional context
I have verified that locally patching `/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.3/snapshots/manager.go` to increase the value allows a state-sync restore to succeed.

While this is safe to patch locally as it doesn't affect consensus, releasing as a hotfix is more difficult because of the [risk of cosmos package version sneaking into JS errors](https://github.com/Agoric/agoric-sdk/issues/7929) which are in consensus.

### PR DESCRIPTION
**Pull request by mhofman**
## Description

Closes: https://github.com/Agoric/agoric-sdk/issues/8325

Increases the snapshot per item size limit when restoring from state-sync, and add a test verifying a payload just below the size can be read.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [x] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed 
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

File: snapshots/manager.go [hunk 1]
```diff
@@ -21,7 +21,9 @@ const (
 
 	chunkBufferSize = 4
 
-	snapshotMaxItemSize = int(64e6) // SDK has no key/value size limit, so we set an arbitrary limit
+	// snapshotMaxItemSize limits the size of both KVStore entries and snapshot
+	// extension payloads during a state-sync restore.
+	snapshotMaxItemSize = int(512e6)
```
Comment (JimLarson) [inline snapshots/manager.go:27]: Cross-reference the same-named constant in `manager_test.go` so we'll remember to update both in tandem.

**Review by JimLarson — APPROVED** [review]
LGTM with one suggested comment.
