### PR TITLE
fix(baseapp): signal then panic at halt-height

### LINKED ISSUE #8326: cosmos halt config might still advance state
## Describe the bug

Cosmos has an `halt-height` and `halt-time` config option to stop the node once the height/time is encountered. However this is only enforce during `Commit` after a DB commit is requested, which allows for the state to go past the requested halt in the following 2 cases:
- The node is started again after stopping at the height/time
- The node is restored from state-sync (which doesn't trigger the normal `Commit` path)

## Expected behavior
Once a halt point is reached, the state no longer changes.

## Additional context
Adding a check for halt conditions in BeginBlock is likely sufficient, as long as the limit check is exclusive instead of inclusive like for the Commit check.

### PR DESCRIPTION
**Pull request by michaelfig**
## Description

Refs: #337, #305
Closes: Agoric/agoric-sdk#8326

Implements both newer Cosmos panic and Agoric-compatible signal behaviour when `--halt-height` is reached. First, try to `SIGINT` self, then `SIGTERM` self, followed by the `CONSENSUS FAILURE!!!` panic. This will stop the state machine in all cases and should exit the process as Agoric expects.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [x] added `!` to the type prefix if API or client breaking change
* [x] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
* [x] provided a link to the relevant issue or specification
* [x] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/build/building-modules/01-intro.md)
* [x] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
* [x] added a changelog entry to `CHANGELOG.md`
* [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
* [x] updated the relevant documentation or specification
* [x] reviewed "Files changed" and left comments if necessary
* [x] run `make lint` and `make test`
* [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage
* [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by JimLarson** [comment]
You can compare to my attempt at a fix: https://github.com/agoric-labs/cosmos-sdk/tree/8326-exit-on-halt

Also note that it will fix Agoric/agoric-sdk#8326

**Comment by michaelfig** [comment]
> You can compare to my attempt at a fix: https://github.com/agoric-labs/cosmos-sdk/tree/8326-exit-on-halt

Here is my annotated version of the code I see there today:
```go
// halt attempts to gracefully shutdown the node via SIGINT and SIGTERM falling
// back on os.Exit if both fail.
func (app *BaseApp) halt() {
	app.logger.Info("halting node per configuration", "height", app.haltHeight, "time", app.haltTime)

	p, err := os.FindProcess(os.Getpid())
	if err == nil {
		// attempt cascading signals in case SIGINT fails (os dependent)
		sigIntErr := p.Signal(syscall.SIGINT)
		sigTermErr := p.Signal(syscall.SIGTERM)

		if sigIntErr == nil || sigTermErr == nil {
			// mfig: sigIntErr and sigTermErr are always nil if the process
			// was found and the signal was sent.  It has nothing to do with
			// how the process handles the signal, thus just returning here
			// does not prevent new blocks from being produced.  A panic
			// is the most appropriate way to prevent further progress.
			return
		}
	}

	// Resort to exiting immediately if the process could not be found or killed
	// via SIGINT/SIGTERM signals.
	app.logger.Info("failed to send SIGINT/SIGTERM; exiting...")
	os.Exit(0) // mfig: this should not be a 0 (success) exit code
}
```

File: baseapp/abci.go [hunk 1]
```diff
@@ -312,6 +314,37 @@ func (app *BaseApp) deliverTxWithoutEventHistory(req abci.RequestDeliverTx) (res
 	}
 }
 
+// checkHalt checkes if height or time exceeds halt-height or halt-time respectively.
```
Comment (gibson042) [inline baseapp/abci.go]:
```suggestion
// checkHalt forces a process exit if height or time exceeds halt-height or halt-time respectively.
```

File: baseapp/abci.go [hunk 2]
```diff
@@ -312,6 +314,37 @@ func (app *BaseApp) deliverTxWithoutEventHistory(req abci.RequestDeliverTx) (res
...
+func (app *BaseApp) checkHalt(height int64, time time.Time) {
+	var halt bool
+	switch {
+	case app.haltHeight > 0 && uint64(height) > app.haltHeight:
+		halt = true
+
+	case app.haltTime > 0 && time.Unix() > int64(app.haltTime):
```
Comment (gibson042) [inline baseapp/abci.go]: Isn't this invalid? [`time.Unix`](https://pkg.go.dev/time#Unix) requires POSIX epoch timestamp input in the form of `sec` and `nsec` arguments, and returns a `time.Time` which is incomparable with `int64`.
```suggestion
	case app.haltTime > 0 && time.Now().Unix() > int64(app.haltTime):
```
(but I'm uncomfortable with using local time rather than block time for this)

File: baseapp/abci.go [hunk 3]
```diff
@@ -312,6 +314,37 @@ func (app *BaseApp) deliverTxWithoutEventHistory(req abci.RequestDeliverTx) (res
...
+		halt = true
+	}
```
Comment (gibson042) [inline baseapp/abci.go]: `switch` seems too verbose here.
```suggestion
	halt := (app.haltHeight > 0 && uint64(height) > app.haltHeight) ||
		(app.haltTime > 0 && time.Unix() > int64(app.haltTime))
```
or
```suggestion
	var halt bool
	if app.haltHeight > 0 && uint64(height) > app.haltHeight {
		halt = true
	} else if app.haltTime > 0 && time.Unix() > int64(app.haltTime) {
		halt = true
	}
```

**Review by gibson042 — CHANGES_REQUESTED** [review]
As noted, I'm uncomfortable with using something other than block time to establish "now". Is there a way to get a block context into the function?

File: baseapp/abci.go (hunk 1 above)
Comment (michaelfig) [reply baseapp/abci.go]: Thanks, I've rephrased.

File: baseapp/abci.go (hunk 2 above)
Comment (michaelfig) [reply baseapp/abci.go]: Ah.  You were misled by the fact the call wasn't using a static function of the `time` package, because that package was shadowed by `checkHalt`'s `time` argument.  So, it was actually using the argument's instance method, [`Time.Unix`](https://pkg.go.dev/time#Time.Unix).  To avoid this confusion, I've renamed the argument to `tm` instead.

File: baseapp/abci.go (hunk 3 above)
Comment (michaelfig) [reply baseapp/abci.go]: Thanks!

**Comment by michaelfig** [comment]
> I'm uncomfortable with using something other than block time to establish "now". Is there a way to get a block context into the function?

The CometBFT block header as supplied to `app.BeginBlock` is exactly what [calls `checkHalt` with in-consensus arguments](https://github.com/agoric-labs/cosmos-sdk/blob/ad59089b9f07ae61754fc0055bb6e6dacf1d1c3e/baseapp/abci.go#L142):
```go
 	app.checkHalt(req.Header.Height, req.Header.Time)
```

File: baseapp/abci.go [hunk 4]
```diff
@@ -312,6 +314,40 @@ func (app *BaseApp) deliverTxWithoutEventHistory(req abci.RequestDeliverTx) (res
 	}
 }
 
+// checkHalt forces a state machine halt and attempts to kill the current
+// process if height or tm exceeds halt-height or halt-time respectively.
+func (app *BaseApp) checkHalt(height int64, tm time.Time) {
```
Comment (gibson042) [inline baseapp/abci.go]: Suggestions for further clarification:
```suggestion
// checkHalt forces a state machine halt and attempts to kill the current
// process if block height or timestamp exceeds halt-height or halt-time respectively.
func (app *BaseApp) checkHalt(blockHeight int64, blockTime time.Time) {
```

File: baseapp/abci.go [hunk 5]
```diff
@@ -312,6 +314,40 @@ func (app *BaseApp) deliverTxWithoutEventHistory(req abci.RequestDeliverTx) (res
...
+	} else if app.haltTime > 0 && tm.Unix() > int64(app.haltTime) {
+		// time to halt has passed
+		halt = true
+	}
+
+	if !halt {
+		return
+	}
+
+	app.logger.Info("halt per configuration", "height", app.haltHeight, "time", app.haltTime)
```
Comment (gibson042) [inline baseapp/abci.go]:
```suggestion
	app.logger.Info("halt per configuration", "haltHheight", app.haltHeight, "haltTime", app.haltTime, "blockHeight", height, "blockTime", tm)
```

**Review by gibson042 — APPROVED** [review]

**Comment by mhofman** [comment]
FYI, the `checkHalt` from #305 (restored here) was an unmodified port of https://github.com/cosmos/cosmos-sdk/pull/16639. That said newer versions of cosmos-sdk take a slightly different approach, so I'm totally ok deviating from the upstream patch as we'll have to re-integrate it anyway.

Overall LGTM, sorry for dropping the ball on this review.
